[package]
name = "axum-skeleton"
version = "0.1.0"
edition = "2021"
authors = ["Mathieu Hardy <mhardy2008@gmail.com>"]
description = "An Axum skeleton to start backend web application"
readme = "README.md"
homepage = "https://github.com/mathieuhardy/axum-skeleton"
repository = "https://github.com/mathieuhardy/axum-skeleton"
license-file = "LICENSE.txt"

[workspace]
members = [
  "crates/database",
  "crates/server",
]

[dependencies]
dotenv = "0.15.0"
env_logger = "0.10.2"
tokio = { version = "1.35.1", features = ["full"] }

server = { path = "crates/server", features = ["k8s", "sanity"] }
