[package]
name = "axum-skeleton"
version = "0.1.0"
edition = "2021"
authors = ["Mathieu Hardy <mhardy2008@gmail.com>"]
description = "An Axum skeleton to start backend web application"
readme = "README.md"
homepage = "TODO"
repository = "TODO"
license-file = "LICENSE.txt"
#build = "build.rs"

[workspace]
members = [
  "crates/database",
  "crates/server",
]

[dependencies]
dotenv = "0.15.0"
env_logger = "0.10.2"
tokio = { version = "1.35.1", features = ["full"] }

server = { path = "crates/server" }
