# TODO: add output directories to isolate builds

[env]

# Common
ROOT = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"
TARGET_DIR = "${ROOT}/target"
SCRIPTS_DIR = "${ROOT}/scripts"

NC = '\033[0m'
BY = '\033[1;33m'
BV = '\033[1;35m'

CARGO_DEFAULT_OPTS="--workspace --all-features --locked"

# Documentation specifics
DOCS_OUTPUT_DIR = "${TARGET_DIR}/doc"
DOCS_COV_RESULTS = "${DOCS_OUTPUT_DIR}/coverage.txt"
DOCS_COV_HTML = "${DOCS_OUTPUT_DIR}/coverage.html"

# Tests specifics
TESTS_COV_HTML = "tarpaulin-report.html"

# Sanity
SAN_OUTPUT_DIR = "${TARGET_DIR}/sanity"
SAN_INPUT_BUILD_TIMINGS = "${TARGET_DIR}/cargo-timings/cargo-timing.html"

# ------------------------------------------------------------------------------
# Show help by default
# ------------------------------------------------------------------------------

[tasks.default]
workspace = false
clear = true
script = '''
echo "${BY}Available commands:${NC}\n"
echo "  ${BV}build-timings${NC}       Show build timings"
echo ""
echo "  ${BV}clippy${NC}              Run cargo clippy"
echo ""
echo "  ${BV}cov-docs${NC}            Generate documentation coverage results"
echo "  ${BV}cov-docs-show${NC}       Show the HTML results of the documentation coverage"
echo ""
echo "  ${BV}doc${NC}                 Generate documentations for the crates"
echo ""
echo "  ${BV}crates-audit${NC}        Make an audit of the crates"
echo "  ${BV}crates-bloats${NC}       Show the list of crates inside the binary with their size"
echo "  ${BV}crates-licenses${NC}     Show the list of licenses by crates"
echo "  ${BV}crates-duplicates${NC}   Show the list of duplicated crates"
echo "  ${BV}crates-unused${NC}       Show the list of unused crates"
echo "  ${BV}crates-upgradables${NC}  Show the list of upgradable crates"
echo ""
echo "  ${BV}sanity${NC}              Generate all reports used for the sanity dashboard"
echo ""
echo "  ${BV}cov-tests${NC}           Generate tests coverage results"
echo "  ${BV}cov-tests-show${NC}      Show the HTML results of the tests coverage"
'''

# ------------------------------------------------------------------------------
# Generate a report with build timings
# ------------------------------------------------------------------------------

[tasks.build-timings]
workspace = false
command = "cargo"
args = ["build", "--timings"]

# ------------------------------------------------------------------------------
# Run clippy analysis
# ------------------------------------------------------------------------------

[tasks.clippy-bootstrap]
workspace = false
private = true
script = '''
if ! command -v cargo-clippy 1>/dev/null 2>&1
then
    rustup component add clippy
fi
'''

[tasks.clippy]
workspace = false
dependencies = ["clippy-bootstrap"]
command = "cargo"
args = [
  "clippy",
  "--workspace",
  "--all-targets",
  "--all-features",
  "--locked",
  "--color", "always",
  "--keep-going",
  "-Z", "unstable-options",
  "--offline"
]

# ------------------------------------------------------------------------------
# Perform an audit of the crates
# ------------------------------------------------------------------------------

[tasks.crates-audit-bootstrap]
workspace = false
private = true
script = '''
if ! command -v cargo-audit 1>/dev/null 2>&1
then
    cargo install cargo-audit
fi
'''

[tasks.crates-audit]
workspace = false
dependencies = ["crates-audit-bootstrap"]
command = "cargo"
args = ["audit"]

[tasks.crates-audit-json]
workspace = false
dependencies = ["crates-audit-bootstrap"]
script = '''
cargo audit --json > ${SAN_OUTPUT_DIR}/crates-audit.json || /bin/true

echo "🟢 ${B_WHITE}Done: ${SAN_OUTPUT_DIR}/crates-audit.json${NC}"
'''

# ------------------------------------------------------------------------------
# Show crates bloats
# ------------------------------------------------------------------------------

[tasks.crates-bloats-bootstrap]
workspace = false
private = true
script = '''
if ! command -v cargo-bloat 1>/dev/null 2>&1
then
    cargo install cargo-bloat
fi
'''

[tasks.crates-bloats]
workspace = false
dependencies = ["crates-bloats-bootstrap"]
script = '''
${SCRIPTS_DIR}/sanity/crates/bloats.py --text
'''

[tasks.crates-bloats-json]
workspace = false
dependencies = ["crates-bloats-bootstrap"]
script = '''
${SCRIPTS_DIR}/sanity/crates/bloats.py 1>${SAN_OUTPUT_DIR}/crates-bloats.json 2>/dev/null

echo "🟢 ${B_WHITE}Done: ${SAN_OUTPUT_DIR}/crates-bloats.json${NC}"
'''

# ------------------------------------------------------------------------------
# Show crates licenses
# ------------------------------------------------------------------------------

[tasks.crates-licenses-bootstrap]
workspace = false
private = true
script = '''
if ! command -v cargo-license 1>/dev/null 2>&1
then
    cargo install cargo-license
fi
'''

[tasks.crates-licenses]
workspace = false
dependencies = ["crates-licenses-bootstrap"]
command = "cargo"
args = ["license"]

[tasks.crates-licenses-json]
workspace = false
dependencies = ["crates-licenses-bootstrap"]
script = '''
cargo license --json > ${SAN_OUTPUT_DIR}/crates-licenses.json || /bin/true

echo "🟢 ${B_WHITE}Done: ${SAN_OUTPUT_DIR}/crates-licenses.json${NC}"
'''

# ------------------------------------------------------------------------------
# Show duplicated crates
# ------------------------------------------------------------------------------

[tasks.crates-duplicates]
workspace = false
script = '''
${SCRIPTS_DIR}/sanity/crates/duplicates.py --text
'''

[tasks.crates-duplicates-json]
workspace = false
script = '''
rm -f ${SAN_OUTPUT_DIR}/crates-duplicates.json

${SCRIPTS_DIR}/sanity/crates/duplicates.py > ${SAN_OUTPUT_DIR}/crates-duplicates.json

echo "🟢 ${B_WHITE}Done: ${SAN_OUTPUT_DIR}/crates-duplicates.json${NC}"
'''

# ------------------------------------------------------------------------------
# Show unused crates
# ------------------------------------------------------------------------------

[tasks.crates-unused-bootstrap]
workspace = false
private = true
script = '''
if ! command -v cargo-machete 1>/dev/null 2>&1
then
    cargo install cargo-machete
fi
'''

[tasks.crates-unused]
workspace = false
dependencies = ["crates-unused-bootstrap"]
command = "cargo"
args = ["machete"]

[tasks.crates-unused-json]
workspace = false
dependencies = ["crates-unused-bootstrap"]
script = '''
rm -f ${SAN_OUTPUT_DIR}/crates-unused.txt

cargo machete 1>${SAN_OUTPUT_DIR}/crates-unused.txt 2>/dev/null | true

echo "🟢 ${B_WHITE}Done: ${SAN_OUTPUT_DIR}/crates-unused.txt${NC}"
'''

# ------------------------------------------------------------------------------
# Show upgradable crates
# ------------------------------------------------------------------------------

[tasks.crates-upgradables-bootstrap]
workspace = false
private = true
script = '''
if ! command -v cargo-outdated 1>/dev/null 2>&1
then
    cargo install cargo-outdated
fi
'''

[tasks.crates-upgradables]
workspace = false
dependencies = ["crates-upgradables-bootstrap"]
script = '''
${SCRIPTS_DIR}/sanity/crates/upgradables.py --text
'''

[tasks.crates-upgradables-json]
workspace = false
dependencies = ["crates-upgradables-bootstrap"]
script = '''
rm -f ${SAN_OUTPUT_DIR}/crates-upgradables.json

${SCRIPTS_DIR}/sanity/crates/upgradables.py > ${SAN_OUTPUT_DIR}/crates-upgradables.json

echo "🟢 ${B_WHITE}Done: ${SAN_OUTPUT_DIR}/crates-upgradables.json${NC}"
'''

# ------------------------------------------------------------------------------
# Sanity reports generation
# ------------------------------------------------------------------------------

[tasks.sanity-setup]
workspace = false
script = '''
mkdir -p ${SAN_OUTPUT_DIR}
'''

[tasks.sanity]
workspace = false
dependencies = [
    "sanity-setup",
    "build-timings",
    "cov-docs",
    "cov-tests",
    "crates-audit-json",
    "crates-bloats-json",
    "crates-duplicates-json",
    "crates-licenses-json",
    "crates-unused-json",
    "crates-upgradables-json"
]
script.pre = '''
mkdir -p ${SAN_OUTPUT_DIR}
echo "🟢 ${B_WHITE}Create output directory: ${SAN_OUTPUT_DIR}${NC}"
'''
script.main = '''
cp ${SAN_INPUT_BUILD_TIMINGS} ${SAN_OUTPUT_DIR}/build-timings.html
echo "🟢 ${B_WHITE}Done: ${SAN_OUTPUT_DIR}/build-timings.html${NC}"

cp ${DOCS_COV_HTML} ${SAN_OUTPUT_DIR}/docs-coverage.html
echo "🟢 ${B_WHITE}Done: ${SAN_OUTPUT_DIR}/docs-coverage.html${NC}"

cp ${TESTS_COV_HTML} ${SAN_OUTPUT_DIR}/tests-coverage.html
echo "🟢 ${B_WHITE}Done: ${SAN_OUTPUT_DIR}/tests-coverage.html${NC}"
'''

# ------------------------------------------------------------------------------
# Documentations generation
# ------------------------------------------------------------------------------

[tasks.doc]
workspace = false
command = "cargo"
args = [
    "doc",
    "--workspace",
    "--all-features",
    "--locked",
    "--offline",
    "--no-deps"
]

# ------------------------------------------------------------------------------
# Documentation coverage targets
# ------------------------------------------------------------------------------

# Generate documentation coverage results
[tasks.cov-docs-build]
workspace = false
private = true
env.RUSTDOCFLAGS = "-Zunstable-options --show-coverage"
script.pre = '''
mkdir -p ${DOCS_OUTPUT_DIR}
echo "🟢 ${B_WHITE}Create output directory: ${DOCS_OUTPUT_DIR}${NC}"
'''
script.main = '''
cargo doc -j 1 ${CARGO_DEFAULT_OPTS} --no-deps --document-private-items 1>${DOCS_COV_RESULTS} 2>&1
'''
script.post = '''
echo "🟢 ${B_WHITE}Results generated: ${DOCS_COV_RESULTS}${NC}"
'''

# Convert the coverage results to HTML
[tasks.cov-docs-html]
workspace = false
private = true
script.main = '''
${ROOT}/scripts/sanity/coverage/doc-coverage-2-html.py ${DOCS_COV_RESULTS} ${DOCS_COV_HTML}
'''
script.post = '''
echo "🟢 ${B_WHITE}Results converted to HTML: ${DOCS_COV_HTML}${NC}"
'''

# Show the documentation coverage report generated
[tasks.cov-docs-show]
workspace = false
script = '''
open ${DOCS_COV_HTML}
'''

# Generate all documentation and the HTML coverage report
[tasks.cov-docs]
workspace = false
run_task = { name = [
    "cov-docs-build",
    "cov-docs-html"
] }

# ------------------------------------------------------------------------------
# Tests coverage targets
# ------------------------------------------------------------------------------

[tasks.cov-tests-bootstrap]
workspace = false
private = true
script = '''
if ! command -v cargo-tarpaulin 1>/dev/null 2>&1
then
    cargo install cargo-tarpaulin
fi
'''

# Show the test coverage report generated
[tasks.cov-tests-show]
workspace = false
script = '''
open ${TESTS_COV_HTML}
'''

# Generate the tests coverage report
[tasks.cov-tests]
workspace = false
dependencies = ["cov-tests-bootstrap"]
script.main = '''
cargo tarpaulin ${CARGO_DEFAULT_OPTS} --all-targets -o html
'''
script.post = '''
echo "🟢 ${B_WHITE}Results generated: ${TESTS_COV_HTML}${NC}"
'''
