[package]
name = "test-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = { version = "0.15.0", default-features = false }
reqwest = { version = "0.11.23", default-features = false, features = ["json"] }
tokio = { version = "1.35.1", default-features = false, features = ["full"] }

test-utils-derives = { path = "derives", default-features = false }
server = { path = "../server", default-features = false }

[features]
derives = []
