[package]
name = "database"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
walkdir = "2.4.0"

[dependencies]
chrono = { version = "0.4.31", features = ["serde"] }
log = "0.4.20"
serde = { version = "1.0.195", features = ["derive"] }
serde_with = "3.5.0"
sqlx = { version = "0.7.3", features = ["chrono", "uuid", "runtime-tokio"] }
thiserror = "1.0.56"
uuid = { version = "1.6.1", features = ["serde", "v4"] }

derives = { path = "derives" }
