[package]
name = "database"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
walkdir = "2.4.0"

[dependencies]
chrono = { version = "0.4.31", features = ["serde"] }
serde = { version = "1.0.195", features = ["derive"] }
#sqlx = { version = "0.7.3", features = ["postgres", "runtime-tokio"] }
sqlx = { version = "0.7.3", features = ["chrono", "uuid"] }
#sqlx = "0.7.3"
uuid = { version = "1.6.1", features = ["serde", "v4"] }
