[package]
name = "database"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
walkdir = "2.4.0"

[dependencies]
chrono = { version = "0.4.31", default-features = false, features = ["serde"] }
serde = { version = "1.0.195", default-features = false, features = ["derive"] }
serde_with = { version = "3.5.0", default-features = false, features = ["macros"] }
sqlx = { version = "0.7.3", default-features = false, features = ["chrono", "uuid", "runtime-tokio"] }
thiserror = { version = "1.0.56", default-features = false }
tracing = { version = "0.1.40", default-features = false, features = ["attributes", "log", "std"] }
uuid = { version = "1.6.1", default-features = false, features = ["serde", "v4"] }

database-derives = { path = "derives", default-features = false }

[dev-dependencies]
tokio = { version = "1.35.1", default-features = false, features = ["full"] }
