[package]
name = "database-derives"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = { version = "1.0.35", default-features = false }
syn = { version = "2.0.48", default-features = false }
