[package]
name = "common-core"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true, default-features = false, features = ["json"] }
serde = { workspace = true, default-features = false, features = ["derive"] }
