[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
project-root = { version = "0.2.2", default-features = false }
thiserror = { version = "1.0.56", default-features = false }

[features]
fs = []
