application:
  port: 8080
  timeout: 15

cors:
  headers:
    - accept
    - authorization
    - origin
  methods:
    - delete
    - get
    - patch
    - post
    - put

password:
  pattern:
    digit: true
    lowercase: true
    uppercase: true
    special: true
    spaces: false
    min_length: 8
    max_length: null
