[package]
name = "k8s"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true, default-features = false, features = ["http1"] }

common-state = { workspace = true, default-features = false }
