[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.4", default-features = false, features = ["form", "http2", "json", "macros", "query", "tokio"] }
config = { version = "0.13.4", default-features = false, features = ["yaml"] }
env_logger = { version = "0.10.2", default-features = false }
log = { version = "0.4.20", default-features = false }
serde = { version = "1.0.195", default-features = false, features = ["derive"] }
serde_with = { version = "3.5.0", default-features = false, features = ["macros"] }
sqlx = { version = "0.7.3", default-features = false, features = ["macros", "postgres", "runtime-tokio", "tls-native-tls", "uuid"] }
thiserror = { version = "1.0.56", default-features = false }
tokio = { version = "1.35.1", default-features = false, features = ["full"] }
tower-http = { version = "0.5.1", default-features = false, features = ["cors"] }

database = { path = "../database", default-features = false }

[dev-dependencies]
serial_test = { version = "3.0.0", default-features = false }
test-utils = { path = "../test-utils", default-features = false, features = ["derives"] }
urlencoding = { version = "2.1.3", default-features = false }

[features]
k8s = []
