[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
config = { version = "0.13.4", features = ["yaml"] }
env_logger = "0.10.2"
log = "0.4.20"
serde = { version = "1.0.195", features = ["derive"] }
sqlx = { version = "0.7.3", features = ["postgres", "runtime-tokio"] }
thiserror = "1.0.56"
tokio = { version = "1.35.1", features = ["full"] }

database = { path = "../database" }
