name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  POSTGRES_USER: demo
  POSTGRES_PASSWORD: demo
  POSTGRES_DB: axum_test
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432

jobs:
  # Check that the project can be build in release mode
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust environment
        uses: moonrepo/setup-rust@v1
        with:
          cache-target: release
          bins: cargo-nextest, sqlx-cli

      - name: Install libpq
        run: |
          sudo apt-get install libpq-dev -y

      - name: Setup database
        env:
          DATABASE_URL: postgres://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@${{ env.POSTGRES_HOST }}:${{ env.POSTGRES_PORT }}/${{ env.POSTGRES_DB }}
        run: |
          sqlx database create
          sqlx migrate run --source ./crates/database/migrations

      - name: Build release
        env:
          DATABASE_URL: postgres://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@${{ env.POSTGRES_HOST }}:${{ env.POSTGRES_PORT }}/${{ env.POSTGRES_DB }}
        run: |
          cargo build --release --workspace --all-targets --all-features --locked

  # Run clippy on project
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust environment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: moonrepo/setup-rust@v1
        with:
          cache-target: release
          bins: cargo-make, cargo-nextest, sqlx-cli
          components: clippy

      - name: Setup database
        env:
          DATABASE_URL: postgres://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@${{ env.POSTGRES_HOST }}:${{ env.POSTGRES_PORT }}/${{ env.POSTGRES_DB }}
        run: |
          sqlx database create
          sqlx migrate run --source ./crates/database/migrations

      - name: Run clippy
        env:
          DATABASE_URL: postgres://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@${{ env.POSTGRES_HOST }}:${{ env.POSTGRES_PORT }}/${{ env.POSTGRES_DB }}
        run: |
          cargo clippy --release --workspace --all-targets --all-features --locked

  # Run linter to check the code formating
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust environment
        uses: moonrepo/setup-rust@v1
        with:
          cache-target: release
          components: rustfmt

      - name: Run linter
        run: |
          cargo fmt --all -- --check

  # Run unit tests
  tests:
    name: Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust environment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: moonrepo/setup-rust@v1
        with:
          cache-target: release
          bins: cargo-nextest, sqlx-cli

      - name: Install libpq
        run: |
          sudo apt-get install libpq-dev -y

      - name: Setup database
        env:
          DATABASE_URL: postgres://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@${{ env.POSTGRES_HOST }}:${{ env.POSTGRES_PORT }}/${{ env.POSTGRES_DB }}
        run: |
          sqlx database create
          sqlx migrate run --source ./crates/database/migrations

      - name: Dotenv
        run: |
          cp .env.sample .env

      - name: Run unit tests
        env:
          DATABASE_URL: postgres://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@${{ env.POSTGRES_HOST }}:${{ env.POSTGRES_PORT }}/${{ env.POSTGRES_DB }}
        run: |
          cargo nextest run --release --workspace --all-targets --all-features --locked
